# Generated by Django 5.1.6 on 2025-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_viewer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=255
            ),
        ),
    ]
