# Generated by Django 5.1.6 on 2025-03-05 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_viewer", "0002_uploadedpdf_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="uploadedpdf",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
